title: Spode's Abode
description: Andrew Spode's retro computing articles and eBay shop
theme: jekyll-theme-minimal
logo: /assets/img/Logo-White-Background-Circle-4K-Smaller.png
url: https://spodesabode.com
collections:
  articles:
    output: true
    permalink: /articles/:path
defaults:
  - scope:
      path: ""
      type: "articles"
    values:
      layout: "article"
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
include:
  - _next