  name: Deploy Site with Shop
  on:
    repository_dispatch:
      types: [deploy_shop]

  permissions:
    contents: read
    pages: write
    id-token: write

  jobs:
    build-and-deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Setup Ruby
          uses: ruby/setup-ruby@v1
          with:
            ruby-version: '3.1'
            bundler-cache: true

        - name: Build Jekyll site
          run: bundle exec jekyll build

        - name: Add shop (placeholder for now)
          run: |
            mkdir -p _site/shop
            echo "<h1>Shop coming soon</h1>" > _site/shop/index.html

        - name: Configure Pages
          uses: actions/configure-pages@v5

        - name: Upload Pages artifact
          uses: actions/upload-pages-artifact@v3
          with:
            path: '_site'

        - name: Deploy to GitHub Pages
          uses: actions/deploy-pages@v4
